### ISSUE TITLE
Allow mentioning someone in a comment

### ISSUE THREAD

**Issue by jimcullenaus** [GlobalX/pockybot#17] opened 2019-01-03 23:14 UTC

**Comment by jimcullenaus** [comment] 2019-01-03 23:30
It seems to do this already?

But the mentioned person is left out of the stored comment. i.e. `@PockyBot peg @Person1 for helping @Person2 with stuff` has the stored `comment` of `for helping  with stuff`

**Comment by Evangelinexx** [comment] 2019-01-15 23:12
This seems to be a duplicate of #16

**Closed** 2019-01-17 06:30 UTC
Labels: bug
